### PR TITLE
some initial sample data

### PR DESCRIPTION
**Pull request by amfred**

### CODE REVIEW

**Comment by hemajv** [comment]
this LGTM :+1:

**Comment by krook** [comment]
@amfred What is the source of this data? It seems to include personally identifiable information.

**Comment by hemajv** [comment]
the `Guilty_Pleas_and_Trials_by_Type_of_Crime.xlsx` is from https://ida.ussc.gov/

**Comment by amfred** [comment]
The Case Data and Questionnaire is randomly generated mock data from Mockaroo: https://www.mockaroo.com/help/terms_of_use

**Comment by krook** [comment]
Thanks @amfred !

**Comment by bbbozzz** [comment]
We have an update to the data from one of our team members on the Bias Detection project, and a general capabilities to simulate more, currently requiring Python and Jupyer Notebook skills. I will get the data to you in Slack.

**Pull request merged**
